version: '2'
services:
  web:
    image: phundament/nginx-one:1.9-5.1.1
    environment:
      - FASTCGI_PASS_HOST=php
    ports:
      - '8100:80'
    volumes:
      - ./_host_volumes/app/web:/app/web:delegated
  php:
    build:
      dockerfile: Dockerfile-debian
      context: 'php'
      args:
        - PHP_BASE_IMAGE_VERSION=7.3-fpm
    image: local/yiisoftware/yii2-php:7.3-fpm
    container_name: app
    environment:
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    volumes:
      - ./tests:/tests:delegated
      - ./_host_volumes/app:/app:delegated
      - ./.composer-docker/cache:/root/.composer/cache:delegated
    links:
        - mysql
    ports:
      - '8000:80'
  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - "3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    networks: 
      - default
